### ISSUE TITLE
Show annotations per component

### ISSUE THREAD

**Issue by marksilvis** [bd2kccd/ccd-annotations-cytoscape#49]
Annotations should be shown per component.

Ideas:

- Show all for selected component(s)
- Right-click > Show all annotations

**Comment by BarbaNikos** [comment]
@marksilvis as I mentioned last Friday, I have added methods `getAnnotationOnNode` and `getAnnotationOnEdge` in the `StorageDelegate`. Aren't those two enough to handle the union/intersection of annotations? Currently, I have creted the method `getAnnotationToEntities` that returns the union of annotations. The intersection is simply done by calling `getAnnotationOnNode` for each node/edge, and the executing Java's `Set.union` method on the two collections.

**Comment by marksilvis** [comment]
@BarbaNikos You're right, these queries will be sufficient for my task. I will continue with my plan of adding two buttons: one to show the union of annotations on all selected components, and one for the intersection.

**Comment by BarbaNikos** [comment]
@marksilvis I located a bug in my code and before I try any fixes, I wanted to discuss it with you. In order to retrieve the union/intersection of annotations on a given collection of nodes and/or edges, I create two `Set<AnnotToEntity>` objects, one for nodes and one for edges. Then, to get the union, I call `Set.addAll(Set<AnnotToEntity> other)` and return the result. 

However, in the case of union, this will return duplicate annotations, and in the case of intersection some will be omitted. The reason for this is that Java's `HashSet` uses a hash produced on the whole `AnnotToEntity` object. As a result, if two different components have a value on the same annotation id, they will be omitted from the intersection. 

Therefore, in the case of intersection, `Set<AnnotToEntity>` should be avoided and `Set<UUID>` should be used (where the UUID is the annotation's UUID).

**Comment by marksilvis** [comment]
This is now implemented by searching on selected components. Users have the option to search by union of selected (default) or intersection using the Cytoscape annotation UUID.

**Comment by BarbaNikos** [comment]
@marksilvis before we close this issue, we need to discuss about possible solutions for my last comment. Let's try to find a solution on tomorrow's Hangouts Meeting.
