### ISSUE TITLE
the annotations labels are very close to the node labels

### ISSUE THREAD

**Issue by harryhoch** [bd2kccd/ccd-annotations-cytoscape#55]
can they be moved and modified so as to not obscure the node labels?

**Comment by marksilvis** [comment]
@harryhoch Any annotation can be moved manually be right-clicking and clicking `Edit -> Move Annotation`. Of course, this isn't helpful when automatic relayout is on, since the annotation will move back into an obstructing position when the node is moved. To solve this, we could introduce a slight skew to the annotation position, i.e., add a few points to the y-position after calculating the average.

**Comment by harryhoch** [comment]
I think a bit more default skew might help.

**Comment by BarbaNikos** [comment]
I added random pixel skew on the coordinate generation, when a new annotation is added.
